# Generated by Django 2.0.4 on 2019-07-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testtask_app', '0002_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='run_time',
            field=models.FloatField(verbose_name='运行时长'),
        ),
    ]
